### ISSUE TITLE
最后的步骤写错了

### ISSUE THREAD

**Issue by sijinglei** [naihe138/GraphQL-demo#1]
应该是
git clone https://github.com/naihe138/GraphQL-demo.git
cd GraphQL-demo
npm install  or cnpm i
还要npm install babel-core babel-polyfill babel-preset-latest-node babel-preset-stage-3 --save-dev
最后
npm start

但是还报错！
![image](https://user-images.githubusercontent.com/18141435/34703878-66a99a64-f530-11e7-94c8-c21a96658cab.png)

**Comment by zichen-cici** [comment]
+1

**Comment by naihe138** [comment]
node  start 改正了  谢谢指出来
