### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by greatbody** [naihe138/GraphQL-demo#4]
首先非常感谢repo主分享

提几个建议

1. README是否可以考虑下重写，不要用原来的官方内容，和代码不匹配
2. 配置信息是否可以写详细，比如需要安装什么数据库，你自己用的什么版本的数据库，初始化数据库和数据的步骤

既然贡献给大家参考，那么不妨考虑下我的建议。

谢谢你的努力！

**Comment by lazyTai** [comment]
弱弱问一下 
Mutation 有没有呢~~

**Comment by naihe138** [comment]
@greatbody   @lazyTai   谢谢大佬的建议，这周加上

**Comment by maoliang2271** [comment]
数据库建表、插数据的sql希望能提供下啊 楼主

**Comment by naihe138** [comment]
已经加上  @greatbody @lazyTai @maoliang2271
