### ISSUE TITLE
如何写入MongoDB数据

### ISSUE THREAD

**Issue by mydaoyuan** [naihe138/GraphQL-demo#5]
您好，请问是需要手动在MongoDB写入数据吗，数据的格式是什么样子的呢？
现在运行项目 数据都是空的

**Comment by maxoyed** [comment]
通过请求saveinfo和savestudent接口可以插入数据

**Comment by naihe138** [comment]
@mydaoyuan  通过请求saveinfo和savestudent接口可以插入数据
